name: CI-CD-Pipeline-AWS-Elastic-Beanstalk

env:
  EB_PACKAGE_S3_BUCKET_NAME : "flask-application-package"
  EB_APPLICATION_NAME       : "MyFlask"
  EB_ENVIRONMENTS           : "Myflask-env"
  DEPLOY_PACKAGE_NAME       : "flask_app_${{ github.sha }}.zip"
  AWS_REGION_NAME           : "eu-central-1"

on:
  push:
    branches:
      - master

jobs:
  ci_part:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone our repo
        uses: actions/checkout@v1

      - name: Create ZIP deployment package
        run : zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
